**1 Import train csv**

In [17]:
import numpy as np
import pandas as pd

train_fd = pd.read_csv("/kaggle/input/train-csv/train.csv") #read test
train_fd.head() # print head of the test

id Product ID Type  Air temperature [K]  Process temperature [K]  \
0   0     L50096    L                300.6                    309.6   
1   1     M20343    M                302.6                    312.1   
2   2     L49454    L                299.3                    308.5   
3   3     L53355    L                301.0                    310.9   
4   4     M24050    M                298.0                    309.0   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  TWF  \
0                    1596         36.1              140                0    0   
1                    1759         29.1              200                0    0   
2                    1805         26.5               25                0    0   
3                    1524         44.3              197                0    0   
4                    1641         35.4               34                0    0   

   HDF  PWF  OSF  RNF  
0    0    0    0    0  
1    0    0    0    0  
2    0    0    0    0  
3    0    0    0    0  
4    0    0    0    0

In [18]:
print(train_fd.info()) #colmun info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136429 entries, 0 to 136428
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype  
---  ------                   --------------   -----  
 0   id                       136429 non-null  int64  
 1   Product ID               136429 non-null  object 
 2   Type                     136429 non-null  object 
 3   Air temperature [K]      136429 non-null  float64
 4   Process temperature [K]  136429 non-null  float64
 5   Rotational speed [rpm]   136429 non-null  int64  
 6   Torque [Nm]              136429 non-null  float64
 7   Tool wear [min]          136429 non-null  int64  
 8   Machine failure          136429 non-null  int64  
 9   TWF                      136429 non-null  int64  
 10  HDF                      136429 non-null  int64  
 11  PWF                      136429 non-null  int64  
 12  OSF                      136429 non-null  int64  
 13  RNF                      136429 non-null  int64  
dtypes: f

**2 remove id and product column**

In [19]:
train_fd = train_fd.drop(columns=['id', 'Product ID']) #remove id and product column
train_fd.head()

Type  Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
0    L                300.6                    309.6                    1596   
1    M                302.6                    312.1                    1759   
2    L                299.3                    308.5                    1805   
3    L                301.0                    310.9                    1524   
4    M                298.0                    309.0                    1641   

   Torque [Nm]  Tool wear [min]  Machine failure  TWF  HDF  PWF  OSF  RNF  
0         36.1              140                0    0    0    0    0    0  
1         29.1              200                0    0    0    0    0    0  
2         26.5               25                0    0    0    0    0    0  
3         44.3              197                0    0    0    0    0    0  
4         35.4               34                0    0    0    0    0    0

In [20]:
counts = train_fd['Machine failure'].value_counts() #count of 1 and 0 in machine failure column
print(counts) #print result

Machine failure
0    134281
1      2148
Name: count, dtype: int64


**3 replace H > 0 M > 1 L > 2**

In [21]:
train_fd['Type'] = train_fd['Type'].replace({'H': 0, 'M': 1, 'L': 2}) #replace H > 0 M > 1 L > 2
train_fd.head() # print check

/tmp/ipykernel_33/1181466908.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train_fd['Type'] = train_fd['Type'].replace({'H': 0, 'M': 1, 'L': 2}) #replace H > 0 M > 1 L > 2


Type  Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
0     2                300.6                    309.6                    1596   
1     1                302.6                    312.1                    1759   
2     2                299.3                    308.5                    1805   
3     2                301.0                    310.9                    1524   
4     1                298.0                    309.0                    1641   

   Torque [Nm]  Tool wear [min]  Machine failure  TWF  HDF  PWF  OSF  RNF  
0         36.1              140                0    0    0    0    0    0  
1         29.1              200                0    0    0    0    0    0  
2         26.5               25                0    0    0    0    0    0  
3         44.3              197                0    0    0    0    0    0  
4         35.4               34                0    0    0    0    0    0

**5 MinMaxScaler**

In [22]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler() #MinMaxScaler new object
scaled_data = scaler.fit_transform(train_fd) #fit scalar with data
scaled_df = pd.DataFrame(scaled_data, columns=train_fd.columns) #return with data frame
print(scaled_df.head()) #print after normalization

   Type  Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
0   1.0             0.582418                   0.4750                0.243402   
1   0.5             0.802198                   0.7875                0.339003   
2   1.0             0.439560                   0.3375                0.365982   
3   1.0             0.626374                   0.6375                0.201173   
4   0.5             0.296703                   0.4000                0.269795   

   Torque [Nm]  Tool wear [min]  Machine failure  TWF  HDF  PWF  OSF  RNF  
0     0.443681         0.553360              0.0  0.0  0.0  0.0  0.0  0.0  
1     0.347527         0.790514              0.0  0.0  0.0  0.0  0.0  0.0  
2     0.311813         0.098814              0.0  0.0  0.0  0.0  0.0  0.0  
3     0.556319         0.778656              0.0  0.0  0.0  0.0  0.0  0.0  
4     0.434066         0.134387              0.0  0.0  0.0  0.0  0.0  0.0  


**6 Split 80% train 20% test random**

In [23]:
from sklearn.model_selection import train_test_split
X = scaled_df.drop(columns=['Machine failure'])  # remove column Machine failure before split with test
y = scaled_df['Machine failure'] # save the data from column Machine failure

# Split 80% train 20% test random
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# print train and test shape
print(f"x_train shape: {x_train.shape}")
print(f"x_test shape: {x_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

x_train shape: (109143, 11)
x_test shape: (27286, 11)
y_train shape: (109143,)
y_test shape: (27286,)


**7a coefficients and intercept**

In [24]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression() # create object LogisticRegression
model.fit(x_train, y_train)
W = model.coef_ #coefficients
B = model.intercept_ #intercept

print("W (coefficients):", W)
print("B (intercept):", B)

W (coefficients): [[ 0.26782888  2.38323478 -1.5247079   3.38200558  6.6369562   1.20194905
   8.327412    8.29474729  8.75838535  8.00450503 -0.04536508]]
B (intercept): [-10.87183275]


**7b accuracy precision recall**

In [25]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

y_train_pred = model.predict(x_train)
y_test_pred = model.predict(x_test)

train_accuracy = accuracy_score(y_train, y_train_pred)
train_precision = precision_score(y_train, y_train_pred, pos_label=1)
train_recall = recall_score(y_train, y_train_pred, pos_label=1)

test_accuracy = accuracy_score(y_test, y_test_pred)
test_precision = precision_score(y_test, y_test_pred, pos_label=1)
test_recall = recall_score(y_test, y_test_pred, pos_label=1)

print("Train Accuracy:", train_accuracy)
print("Train Precision:", train_precision)
print("Train Recall:", train_recall)
print("Test Accuracy:", test_accuracy)
print("Test Precision:", test_precision)
print("Test Recall:", test_recall)

Train Accuracy: 0.9961609997892673
Train Precision: 0.992372234935164
Train Recall: 0.7608187134502924
Test Accuracy: 0.9961518727552591
Test Precision: 0.9911504424778761
Test Recall: 0.7671232876712328


**7c Confusion Matrix**

In [26]:
from sklearn.metrics import confusion_matrix

train_confusion_matrix = confusion_matrix(y_train, y_train_pred)

test_confusion_matrix = confusion_matrix(y_test, y_test_pred)

print("Confusion Matrix for Training Data:")
print(train_confusion_matrix)

print("\nConfusion Matrix for Test Data:")
print(test_confusion_matrix)

Confusion Matrix for Training Data:
[[107423     10]
 [   409   1301]]

Confusion Matrix for Test Data:
[[26845     3]
 [  102   336]]


Retest without colmuns 'TWF', 'HDF','PWF','OSF','RNF'

**8 remove 'TWF', 'HDF','PWF','OSF','RNF' columns**

In [27]:
train_fd = train_fd.drop(columns=['TWF', 'HDF','PWF','OSF','RNF']) #remove 'TWF', 'HDF','PWF','OSF','RNF' columns
print(train_fd.head())

scaled_data = scaler.fit_transform(train_fd) #fit scalar with data
scaled_df = pd.DataFrame(scaled_data, columns=train_fd.columns) #return with data frame
print(scaled_df.head()) #print after normalization

   Type  Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
0     2                300.6                    309.6                    1596   
1     1                302.6                    312.1                    1759   
2     2                299.3                    308.5                    1805   
3     2                301.0                    310.9                    1524   
4     1                298.0                    309.0                    1641   

   Torque [Nm]  Tool wear [min]  Machine failure  
0         36.1              140                0  
1         29.1              200                0  
2         26.5               25                0  
3         44.3              197                0  
4         35.4               34                0  
   Type  Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
0   1.0             0.582418                   0.4750                0.243402   
1   0.5             0.802198                 

In [28]:
X = scaled_df.drop(columns=['Machine failure'])  # remove column Machine failure before split with test
y = scaled_df['Machine failure'] # save the data from column Machine failure

# Split 80% train 20% test random
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# print train and test shape
print(f"x_train shape: {x_train.shape}")
print(f"x_test shape: {x_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}") 

x_train shape: (109143, 6)
x_test shape: (27286, 6)
y_train shape: (109143,)
y_test shape: (27286,)


In [29]:
model = LogisticRegression() # create object LogisticRegression
model.fit(x_train, y_train)
W = model.coef_ #coefficients
B = model.intercept_ #intercept

print("W (coefficients):", W)
print("B (intercept):", B)

W (coefficients): [[ 0.39165779  5.64149037 -4.25384637  4.85655489 11.29063732  1.94864934]]
B (intercept): [-13.40779757]


In [30]:
train_confusion_matrix = confusion_matrix(y_train, y_train_pred)

test_confusion_matrix = confusion_matrix(y_test, y_test_pred)

print("Confusion Matrix for Training Data:")
print(train_confusion_matrix)

print("\nConfusion Matrix for Test Data:")
print(test_confusion_matrix)

Confusion Matrix for Training Data:
[[107423     10]
 [   409   1301]]

Confusion Matrix for Test Data:
[[26845     3]
 [  102   336]]


In [31]:
y_train_pred = model.predict(x_train)
y_test_pred = model.predict(x_test)

train_accuracy = accuracy_score(y_train, y_train_pred)
train_precision = precision_score(y_train, y_train_pred, pos_label=1)
train_recall = recall_score(y_train, y_train_pred, pos_label=1)

test_accuracy = accuracy_score(y_test, y_test_pred)
test_precision = precision_score(y_test, y_test_pred, pos_label=1)
test_recall = recall_score(y_test, y_test_pred, pos_label=1)

# הצגת המדדים
print("Train Accuracy:", train_accuracy)
print("Train Precision:", train_precision)
print("Train Recall:", train_recall)
print("Test Accuracy:", test_accuracy)
print("Test Precision:", test_precision)
print("Test Recall:", test_recall)

Train Accuracy: 0.9845981876987072
Train Precision: 0.7636363636363637
Train Recall: 0.02456140350877193
Test Accuracy: 0.9842043538811112
Test Precision: 0.8181818181818182
Test Recall: 0.02054794520547945


**9 Decision Tree and kNN**

**DecisionTreeClassifier**

In [32]:
from sklearn.tree import DecisionTreeClassifier
# Split 80% train 20% test random
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
configuration = [5,8,10,15] #we select 4 configuration and try to make the most accuracy depth for our tree
for i in configuration :#every loop we will try diffrent config
    DecTree_model = DecisionTreeClassifier(max_depth = i, random_state=42) #create tree with i depth
    DecTree_model.fit(x_train, y_train)#fiting
    y_train_pred = DecTree_model.predict(x_train) #make predict for train
    y_test_pred = DecTree_model.predict(x_test) #make predict for test
    #train result
    train_accuracy = accuracy_score(y_train, y_train_pred) #find the accuracy
    train_precision = precision_score(y_train, y_train_pred, pos_label=1) #find the precision
    train_recall = recall_score(y_train, y_train_pred, pos_label=1) #find the recall
    #test result
    test_accuracy = accuracy_score(y_test, y_test_pred) 
    test_precision = precision_score(y_test, y_test_pred, pos_label=1)
    test_recall = recall_score(y_test, y_test_pred, pos_label=1)
    
    train_cm = confusion_matrix(y_train, y_train_pred)
    test_cm = confusion_matrix(y_test, y_test_pred)
    
    print(f"Decision Tree with max_depth={i}")
    print("Train Accuracy:", train_accuracy)
    print("Train Precision:", train_precision)
    print("Train Recall:", train_recall)
    print("Test Accuracy:", test_accuracy)
    print("Test Precision:", test_precision)
    print("Test Recall:", test_recall)
    print("Confusion Matrix for Training Data:")
    print(train_cm)
    print("Confusion Matrix for Test Data:")
    print(test_cm)
    print("\n")

Decision Tree with max_depth=5
Train Accuracy: 0.9864856197832201
Train Precision: 0.6705370101596516
Train Recall: 0.27017543859649124
Test Accuracy: 0.9855237117935938
Test Precision: 0.6149732620320856
Test Recall: 0.2625570776255708
Confusion Matrix for Training Data:
[[107206    227]
 [  1248    462]]
Confusion Matrix for Test Data:
[[26776    72]
 [  323   115]]


Decision Tree with max_depth=8
Train Accuracy: 0.9884005387427504
Train Precision: 0.7466666666666667
Train Recall: 0.3929824561403509
Test Accuracy: 0.9848273840064502
Test Precision: 0.5512820512820513
Test Recall: 0.2945205479452055
Confusion Matrix for Training Data:
[[107205    228]
 [  1038    672]]
Confusion Matrix for Test Data:
[[26743   105]
 [  309   129]]


Decision Tree with max_depth=10
Train Accuracy: 0.9899856152020744
Train Precision: 0.8278427205100957
Train Recall: 0.45555555555555555
Test Accuracy: 0.9850106281609616
Test Precision: 0.5568627450980392
Test Recall: 0.3242009132420091
Confusion Matrix 

**KNeighborsClassifier**

In [34]:
from sklearn.neighbors import KNeighborsClassifier

# Split 80% train 20% test random
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
configuration = [5,8,10,15] #we select 4 configuration and try to make the most accuracy neighbors 
for i in configuration :#every loop we will try diffrent config
    kNN_model = KNeighborsClassifier(n_neighbors= i) #create KNeighborsClassifier with i neighbors
    kNN_model.fit(x_train, y_train)#fiting
    y_train_pred = kNN_model.predict(x_train) #make predict for train
    y_test_pred = kNN_model.predict(x_test) #make predict for test
    #train result
    train_accuracy = accuracy_score(y_train, y_train_pred) #find the accuracy
    train_precision = precision_score(y_train, y_train_pred, pos_label=1) #find the precision
    train_recall = recall_score(y_train, y_train_pred, pos_label=1) #find the recall
    #test result
    test_accuracy = accuracy_score(y_test, y_test_pred) #find the accuracy
    test_precision = precision_score(y_test, y_test_pred, pos_label=1)#find the precision
    test_recall = recall_score(y_test, y_test_pred, pos_label=1)#find the recall
    
    train_cm = confusion_matrix(y_train, y_train_pred)#confusion_matrix for train
    test_cm = confusion_matrix(y_test, y_test_pred)#confusion_matrix for test
    
    print(f"Tree with max_depth={i}")
    print("Train Accuracy:", train_accuracy)
    print("Train Precision:", train_precision)
    print("Train Recall:", train_recall)
    print("Test Accuracy:", test_accuracy)
    print("Test Precision:", test_precision)
    print("Test Recall:", test_recall)
    print("Confusion Matrix for Training Data:")
    print(train_cm)
    print("Confusion Matrix for Test Data:")
    print(test_cm)

Tree with max_depth=5
Train Accuracy: 0.9880706962425442
Train Precision: 0.7873239436619718
Train Recall: 0.32690058479532164
Test Accuracy: 0.9847174375137433
Test Precision: 0.5724137931034483
Test Recall: 0.18949771689497716
Confusion Matrix for Training Data:
[[107282    151]
 [  1151    559]]
Confusion Matrix for Test Data:
[[26786    62]
 [  355    83]]
Tree with max_depth=8
Train Accuracy: 0.9863115362414447
Train Precision: 0.7950819672131147
Train Recall: 0.17017543859649123
Test Accuracy: 0.98530381880818
Test Precision: 0.7228915662650602
Test Recall: 0.136986301369863
Confusion Matrix for Training Data:
[[107358     75]
 [  1419    291]]
Confusion Matrix for Test Data:
[[26825    23]
 [  378    60]]
Tree with max_depth=10
Train Accuracy: 0.9860183429079281
Train Precision: 0.7754491017964071
Train Recall: 0.15146198830409358
Test Accuracy: 0.9847907351755479
Test Precision: 0.6533333333333333
Test Recall: 0.11187214611872145
Confusion Matrix for Training Data:
[[107358    